[project]
name = "recurring-configure-bridge"
authors = ["Stacks Developer"]
description = "Dynamic configuration bridge with recurring update capabilities"
telemetry = false
requirements = []

[contracts.config-manager]
path = "contracts/config-manager.clar"
depends_on = []

[contracts.bridge-router]
path = "contracts/bridge-router.clar"
depends_on = []

[contracts.recurring-updater]
path = "contracts/recurring-updater.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
